name: ETL polish sejm info

on:
  workflow_dispatch:
    inputs:
      TERM:
        description: 'A polish sejm term to get data'
        required: true
        default: 10

jobs:
  etl-deputies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run polish-sejm-check
      run: python etl_polish_sejm.py

    - name: Upload MPs csv file
      uses: actions/upload-artifact@v2
      with:
        name: "mps_term${{ github.event.inputs.TERM }}.csv"
        path: "cache/mps_term${{ github.event.inputs.TERM }}.csv"

    - name: Upload sittings csv file
      uses: actions/upload-artifact@v2
      with:
        name: "sittings_term${{ github.event.inputs.TERM }}.csv"
        path: "cache/sittings_term${{ github.event.inputs.TERM }}.csv"

    - name: Upload voting csv file
      uses: actions/upload-artifact@v2
      with:
        name: "voting_term${{ github.event.inputs.TERM }}.csv"
        path: "cache/voting_term${{ github.event.inputs.TERM }}.csv"

    - name: Upload voting per MP csv file
      uses: actions/upload-artifact@v2
      with:
        name: "voting_per_mp_term${{ github.event.inputs.TERM }}.csv"
        path: "cache/voting_per_mp_term${{ github.event.inputs.TERM }}.csv"